/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user_interface;

import java.awt.Color;

/**
 *
 * @author Kokox (Jorge Aguilar)
 */
public class UI extends javax.swing.JFrame {

    /**
     * Formulario Raíz - UI
     * by Kokox
     */
    
    Color panedefault;
    Color paneClick;
        
    public UI() {
        initComponents();
        
        //Seteo colores del panel por default y clickeado
        panedefault = new Color(245,245,246);
        paneClick = new Color (25,33,36);
        
        //Color por defecto de los paneles laterales izquierdos
        jPanelBtnHome.setBackground(paneClick);
        jPanelBtnHelp.setBackground(panedefault);
        
        //Mostramos el formulario UI_Home desde el inicio
        UI_Home oUIHome = new UI_Home();
        jDesktopPaneMain.add(oUIHome).setVisible(true);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSuperior = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanelIzquierdo = new javax.swing.JPanel();
        jPanelMainHome = new javax.swing.JPanel();
        jPanelBtnHome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelMainHelp = new javax.swing.JPanel();
        jPanelBtnHelp = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDesktopPaneMain = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelSuperior.setBackground(new java.awt.Color(167, 192, 205));
        jPanelSuperior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelSuperiorMouseDragged(evt);
            }
        });
        jPanelSuperior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelSuperiorMousePressed(evt);
            }
        });

        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_interface/baseline_close_black_18dp.png"))); // NOI18N
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(25, 33, 36));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_interface/utp_icono.png"))); // NOI18N
        jLabel3.setText("RUCGLE - Buscador de RUCs en SUNAT");

        javax.swing.GroupLayout jPanelSuperiorLayout = new javax.swing.GroupLayout(jPanelSuperior);
        jPanelSuperior.setLayout(jPanelSuperiorLayout);
        jPanelSuperiorLayout.setHorizontalGroup(
            jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 555, Short.MAX_VALUE)
                .addComponent(lblClose)
                .addContainerGap())
        );
        jPanelSuperiorLayout.setVerticalGroup(
            jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, -1));

        jPanelIzquierdo.setBackground(new java.awt.Color(75, 99, 110));

        jPanelMainHome.setBackground(new java.awt.Color(245, 245, 246));
        jPanelMainHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMainHomeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelMainHomeMousePressed(evt);
            }
        });

        jPanelBtnHome.setBackground(new java.awt.Color(25, 33, 36));

        javax.swing.GroupLayout jPanelBtnHomeLayout = new javax.swing.GroupLayout(jPanelBtnHome);
        jPanelBtnHome.setLayout(jPanelBtnHomeLayout);
        jPanelBtnHomeLayout.setHorizontalGroup(
            jPanelBtnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanelBtnHomeLayout.setVerticalGroup(
            jPanelBtnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(25, 33, 36));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_interface/baseline_house_black_18dp.png"))); // NOI18N
        jLabel1.setText("INICIO");

        javax.swing.GroupLayout jPanelMainHomeLayout = new javax.swing.GroupLayout(jPanelMainHome);
        jPanelMainHome.setLayout(jPanelMainHomeLayout);
        jPanelMainHomeLayout.setHorizontalGroup(
            jPanelMainHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainHomeLayout.createSequentialGroup()
                .addComponent(jPanelBtnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addGap(0, 88, Short.MAX_VALUE))
        );
        jPanelMainHomeLayout.setVerticalGroup(
            jPanelMainHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainHomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
            .addComponent(jPanelBtnHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelMainHelp.setBackground(new java.awt.Color(245, 245, 246));
        jPanelMainHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMainHelpMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelMainHelpMousePressed(evt);
            }
        });

        jPanelBtnHelp.setBackground(new java.awt.Color(25, 33, 36));

        javax.swing.GroupLayout jPanelBtnHelpLayout = new javax.swing.GroupLayout(jPanelBtnHelp);
        jPanelBtnHelp.setLayout(jPanelBtnHelpLayout);
        jPanelBtnHelpLayout.setHorizontalGroup(
            jPanelBtnHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanelBtnHelpLayout.setVerticalGroup(
            jPanelBtnHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(25, 33, 36));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_interface/baseline_help_outline_black_18dp.png"))); // NOI18N
        jLabel2.setText("AYUDA");

        javax.swing.GroupLayout jPanelMainHelpLayout = new javax.swing.GroupLayout(jPanelMainHelp);
        jPanelMainHelp.setLayout(jPanelMainHelpLayout);
        jPanelMainHelpLayout.setHorizontalGroup(
            jPanelMainHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainHelpLayout.createSequentialGroup()
                .addComponent(jPanelBtnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelMainHelpLayout.setVerticalGroup(
            jPanelMainHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBtnHelp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainHelpLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(25, 33, 36));
        jLabel4.setText("Versión: 1.0");

        javax.swing.GroupLayout jPanelIzquierdoLayout = new javax.swing.GroupLayout(jPanelIzquierdo);
        jPanelIzquierdo.setLayout(jPanelIzquierdoLayout);
        jPanelIzquierdoLayout.setHorizontalGroup(
            jPanelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMainHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelMainHelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelIzquierdoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );
        jPanelIzquierdoLayout.setVerticalGroup(
            jPanelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIzquierdoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanelMainHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelMainHelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 613, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        getContentPane().add(jPanelIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 260, 790));

        jDesktopPaneMain.setBackground(new java.awt.Color(245, 245, 246));

        javax.swing.GroupLayout jDesktopPaneMainLayout = new javax.swing.GroupLayout(jDesktopPaneMain);
        jDesktopPaneMain.setLayout(jDesktopPaneMainLayout);
        jDesktopPaneMainLayout.setHorizontalGroup(
            jDesktopPaneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        jDesktopPaneMainLayout.setVerticalGroup(
            jDesktopPaneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPaneMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 72, 730, 750));

        jPanel1.setBackground(new java.awt.Color(75, 99, 110));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 730, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //integrales
    int x, y;
    
    private void jPanelSuperiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSuperiorMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanelSuperiorMousePressed

    private void jPanelSuperiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSuperiorMouseDragged
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx-x, yy-y);
    }//GEN-LAST:event_jPanelSuperiorMouseDragged

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void jPanelMainHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMainHomeMousePressed
        jPanelBtnHome.setBackground(paneClick);
        jPanelBtnHelp.setBackground(panedefault);        
    }//GEN-LAST:event_jPanelMainHomeMousePressed

    private void jPanelMainHelpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMainHelpMousePressed
        jPanelBtnHome.setBackground(panedefault);
        jPanelBtnHelp.setBackground(paneClick);        
    }//GEN-LAST:event_jPanelMainHelpMousePressed

    private void jPanelMainHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMainHomeMouseClicked
        UI_Home oUIHome = new UI_Home();
        jDesktopPaneMain.add(oUIHome).setVisible(true);
    }//GEN-LAST:event_jPanelMainHomeMouseClicked

    private void jPanelMainHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMainHelpMouseClicked
        UI_Help oUIHelp = new UI_Help();
        jDesktopPaneMain.add(oUIHelp).setVisible(true);
    }//GEN-LAST:event_jPanelMainHelpMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPaneMain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBtnHelp;
    private javax.swing.JPanel jPanelBtnHome;
    private javax.swing.JPanel jPanelIzquierdo;
    private javax.swing.JPanel jPanelMainHelp;
    private javax.swing.JPanel jPanelMainHome;
    private javax.swing.JPanel jPanelSuperior;
    private javax.swing.JLabel lblClose;
    // End of variables declaration//GEN-END:variables
}
