/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user_interface;

import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Kokox (Jorge Aguilar)
 */
public class UI_Help extends javax.swing.JInternalFrame  {

    /**
     * Creates new form UI_Help
     */
    public UI_Help(){
        initComponents();
        
        //Fix borde formulario
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);  
        
        //boton URL
        btnGitHubURL.addActionListener(openURL);
        btnGitHubURL.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }
    
    Action openURL = new AbstractAction()
    {
        @Override
        public void actionPerformed(ActionEvent e)
        {
            open();
        }
    };
    
    private static void open() {
      URI gitHubURL;         
      if (Desktop.isDesktopSupported()) {
        try {
          gitHubURL = new URI("https://github.com/theKokox/Rucgle");
          Desktop.getDesktop().browse(gitHubURL);
        } catch (IOException | URISyntaxException e) {
            /* TODO: error handling */ 
        }
      } else { /* TODO: error handling */ }
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnGitHubURL = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(730, 724));

        jPanel1.setBackground(new java.awt.Color(214, 217, 223));
        jPanel1.setPreferredSize(new java.awt.Dimension(730, 730));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_interface/utp_logo_full2.png"))); // NOI18N

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(75, 99, 110));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(245, 245, 246));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Aplicación desarrollada para el curso de \"Programación Orientada a Objetos\".\n\nEl programa crea una conexión a una REST API que, a su vez, obtiene información de\nla Superintendencia Nacional de Aduanas y de Administracion Tributaria (SUNAT).\n\nLa información obtenida es mostrada por interfaz gráfica al usuario final.\n\nEsta aplicación ha sido desarrollada con fines didácticos y el código fuente puede ser \nencontrado en la siguiente dirección:");
        jScrollPane1.setViewportView(jTextArea1);

        btnGitHubURL.setBackground(new java.awt.Color(255, 204, 102));
        btnGitHubURL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGitHubURL.setForeground(new java.awt.Color(75, 99, 110));
        btnGitHubURL.setText("<HTML>GitHub: <FONT color=\\\"#000099\\\"><U>https://github.com/theKokox/Rucgle</U></FONT></HTML>\"");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnGitHubURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(185, 185, 185))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(72, 72, 72)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGitHubURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(259, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGitHubURL;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
