/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user_interface;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.awt.event.ActionEvent;
import java.util.List;
import javafx.beans.binding.BooleanBinding;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingWorker;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import rucgle.Sunat;
import rucgle.SunatJuridica;
import rucgle.SunatNatural;

/**
 *
 * @author Kokox (Jorge Aguilar)
 */
public class UI_Home extends javax.swing.JInternalFrame {

    /**
     * Creates new form UI_Home
     */
    Sunat oSuJuridica;
    Sunat oSuNatural;
    private SwingWorker<Void, Integer> buscarRucWorker = null;
    
    
    public UI_Home() {
        //Inicializa componentes del formulario
        initComponents();
        
        //Fix borde formulario
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);  
        
        //Por defecto, desactiva la animación de carga al inicio del formulario
        lblLoadingAnimation.setVisible(false);    
        //Por defecto, desactiva el texto de carga al inicio del formulario
        lblLoadingText.setVisible(false);
        
        //Tanto txtRucInput y btnBuscarRuc, ejecutarán la misma acción
        txtRucInput.addActionListener(buscarRucAction);
        btnBuscarRuc.addActionListener(buscarRucAction);
        
        //Se le asigna la acción "copyToClipBoard" a todos los botones restantes
        btnRucCp.addActionListener(copyToClipboard);
        btnRazonSocialCp.addActionListener(copyToClipboard);
        btnTipoPersonaCp.addActionListener(copyToClipboard);
        btnCondicionCp.addActionListener(copyToClipboard);
        btnNombreComCp.addActionListener(copyToClipboard);
        btnTipoCp.addActionListener(copyToClipboard);
        btnInscripcionCp.addActionListener(copyToClipboard);
        btnEstadoCp.addActionListener(copyToClipboard);
        btnDireccionCp.addActionListener(copyToClipboard);
        btnSistEmisionCp.addActionListener(copyToClipboard);
        btnActExteriorCp.addActionListener(copyToClipboard);
        btnSistContabCp.addActionListener(copyToClipboard);
        btnEmiElectCp.addActionListener(copyToClipboard);
        btnPLECp.addActionListener(copyToClipboard);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtRucOp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtRazonSocialOp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTipoPersonaOp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCondicionOp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNombreComOp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTipoOp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtInscripcionOp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtEstadoOp = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDireccionOp = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtSistEmisionOp = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtActExteriorOp = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtSistContabOp = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtEmiElectOp = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtPLEOp = new javax.swing.JTextField();
        txtRucInput = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btnBuscarRuc = new javax.swing.JButton();
        btnRazonSocialCp = new javax.swing.JButton();
        btnTipoPersonaCp = new javax.swing.JButton();
        btnCondicionCp = new javax.swing.JButton();
        btnNombreComCp = new javax.swing.JButton();
        btnTipoCp = new javax.swing.JButton();
        btnInscripcionCp = new javax.swing.JButton();
        btnEstadoCp = new javax.swing.JButton();
        btnDireccionCp = new javax.swing.JButton();
        btnSistEmisionCp = new javax.swing.JButton();
        btnActExteriorCp = new javax.swing.JButton();
        btnSistContabCp = new javax.swing.JButton();
        btnEmiElectCp = new javax.swing.JButton();
        btnPLECp = new javax.swing.JButton();
        btnRucCp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblLoadingAnimation = new javax.swing.JLabel();
        btnLiampiarTodo = new javax.swing.JButton();
        lblLoadingText = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(730, 750));

        jPanel1.setBackground(new java.awt.Color(214, 217, 223));
        jPanel1.setPreferredSize(new java.awt.Dimension(730, 730));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(25, 33, 36));
        jLabel2.setText("RUC:");

        txtRucOp.setEditable(false);
        txtRucOp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtRucOp.setForeground(new java.awt.Color(25, 33, 36));
        txtRucOp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRucOp.setText("-");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(25, 33, 36));
        jLabel3.setText("RAZÓN SOCIAL:");

        txtRazonSocialOp.setEditable(false);
        txtRazonSocialOp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtRazonSocialOp.setForeground(new java.awt.Color(25, 33, 36));
        txtRazonSocialOp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRazonSocialOp.setText("-");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(25, 33, 36));
        jLabel4.setText("TIPO DE PERSONA:");

        txtTipoPersonaOp.setEditable(false);
        txtTipoPersonaOp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTipoPersonaOp.setForeground(new java.awt.Color(25, 33, 36));
        txtTipoPersonaOp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTipoPersonaOp.setText("-");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(25, 33, 36));
        jLabel5.setText("CONDICIÓN:");

        txtCondicionOp.setEditable(false);
        txtCondicionOp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCondicionOp.setForeground(new java.awt.Color(25, 33, 36));
        txtCondicionOp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCondicionOp.setText("-");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(25, 33, 36));
        jLabel6.setText("NOMBRE COMERCIAL:");

        txtNombreComOp.setEditable(false);
        txtNombreComOp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNombreComOp.setForeground(new java.awt.Color(25, 33, 36));
        txtNombreComOp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombreComOp.setText("-");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(25, 33, 36));
        jLabel7.setText("TIPO:");

        txtTipoOp.setEditable(false);
        txtTipoOp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTipoOp.setForeground(new java.awt.Color(25, 33, 36));
        txtTipoOp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTipoOp.setText("-");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(25, 33, 36));
        jLabel8.setText("INSCRIPCIÓN:");

        txtInscripcionOp.setEditable(false);
        txtInscripcionOp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtInscripcionOp.setForeground(new java.awt.Color(25, 33, 36));
        txtInscripcionOp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtInscripcionOp.setText("-");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(25, 33, 36));
        jLabel9.setText("ESTADO:");

        txtEstadoOp.setEditable(false);
        txtEstadoOp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtEstadoOp.setForeground(new java.awt.Color(25, 33, 36));
        txtEstadoOp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEstadoOp.setText("-");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(25, 33, 36));
        jLabel10.setText("DIRECCIÓN:");

        txtDireccionOp.setEditable(false);
        txtDireccionOp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtDireccionOp.setForeground(new java.awt.Color(25, 33, 36));
        txtDireccionOp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDireccionOp.setText("-");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(25, 33, 36));
        jLabel11.setText("SISTEMA DE EMISIÓN:");

        txtSistEmisionOp.setEditable(false);
        txtSistEmisionOp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSistEmisionOp.setForeground(new java.awt.Color(25, 33, 36));
        txtSistEmisionOp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSistEmisionOp.setText("-");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(25, 33, 36));
        jLabel12.setText("ACTIVIDAD EXTERIOR:");

        txtActExteriorOp.setEditable(false);
        txtActExteriorOp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtActExteriorOp.setForeground(new java.awt.Color(25, 33, 36));
        txtActExteriorOp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtActExteriorOp.setText("-");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(25, 33, 36));
        jLabel13.setText("SISTEMA DE CONTABILIDAD:");

        txtSistContabOp.setEditable(false);
        txtSistContabOp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSistContabOp.setForeground(new java.awt.Color(25, 33, 36));
        txtSistContabOp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSistContabOp.setText("-");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(25, 33, 36));
        jLabel14.setText("EMISIÓN ELECTRÓNICA:");

        txtEmiElectOp.setEditable(false);
        txtEmiElectOp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtEmiElectOp.setForeground(new java.awt.Color(25, 33, 36));
        txtEmiElectOp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEmiElectOp.setText("-");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(25, 33, 36));
        jLabel15.setText("PLE:");

        txtPLEOp.setEditable(false);
        txtPLEOp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPLEOp.setForeground(new java.awt.Color(25, 33, 36));
        txtPLEOp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPLEOp.setText("-");

        txtRucInput.setBackground(new java.awt.Color(204, 204, 204));
        txtRucInput.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtRucInput.setForeground(new java.awt.Color(75, 99, 110));
        txtRucInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRucInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRucInputKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRucInputKeyTyped(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(75, 99, 110));
        jLabel16.setText("INGRESE RUC O DNI:");

        btnBuscarRuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_interface/baseline_search_black_18dp.png"))); // NOI18N
        btnBuscarRuc.setEnabled(false);

        btnRazonSocialCp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_interface/baseline_content_copy_black_18dp.png"))); // NOI18N
        btnRazonSocialCp.setEnabled(false);

        btnTipoPersonaCp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_interface/baseline_content_copy_black_18dp.png"))); // NOI18N
        btnTipoPersonaCp.setEnabled(false);

        btnCondicionCp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_interface/baseline_content_copy_black_18dp.png"))); // NOI18N
        btnCondicionCp.setEnabled(false);

        btnNombreComCp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_interface/baseline_content_copy_black_18dp.png"))); // NOI18N
        btnNombreComCp.setEnabled(false);

        btnTipoCp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_interface/baseline_content_copy_black_18dp.png"))); // NOI18N
        btnTipoCp.setEnabled(false);

        btnInscripcionCp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_interface/baseline_content_copy_black_18dp.png"))); // NOI18N
        btnInscripcionCp.setEnabled(false);

        btnEstadoCp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_interface/baseline_content_copy_black_18dp.png"))); // NOI18N
        btnEstadoCp.setEnabled(false);

        btnDireccionCp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_interface/baseline_content_copy_black_18dp.png"))); // NOI18N
        btnDireccionCp.setEnabled(false);

        btnSistEmisionCp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_interface/baseline_content_copy_black_18dp.png"))); // NOI18N
        btnSistEmisionCp.setEnabled(false);

        btnActExteriorCp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_interface/baseline_content_copy_black_18dp.png"))); // NOI18N
        btnActExteriorCp.setEnabled(false);

        btnSistContabCp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_interface/baseline_content_copy_black_18dp.png"))); // NOI18N
        btnSistContabCp.setEnabled(false);

        btnEmiElectCp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_interface/baseline_content_copy_black_18dp.png"))); // NOI18N
        btnEmiElectCp.setEnabled(false);

        btnPLECp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_interface/baseline_content_copy_black_18dp.png"))); // NOI18N
        btnPLECp.setEnabled(false);

        btnRucCp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_interface/baseline_content_copy_black_18dp.png"))); // NOI18N
        btnRucCp.setEnabled(false);

        lblLoadingAnimation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_interface/ezgif.com-resize.gif"))); // NOI18N

        btnLiampiarTodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_interface/baseline_clear_all_black_18dp.png"))); // NOI18N
        btnLiampiarTodo.setEnabled(false);
        btnLiampiarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLiampiarTodoActionPerformed(evt);
            }
        });

        lblLoadingText.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblLoadingText.setForeground(new java.awt.Color(25, 33, 36));
        lblLoadingText.setText("Cargando información de SUNAT...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblLoadingAnimation)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblLoadingText)
                                .addGap(37, 37, 37))
                            .addComponent(txtPLEOp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmiElectOp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEstadoOp, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtInscripcionOp, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTipoOp, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtRazonSocialOp, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtRucInput, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnBuscarRuc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnLiampiarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtRucOp, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnRucCp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSistEmisionOp, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDireccionOp, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombreComOp, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCondicionOp, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTipoPersonaOp, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtActExteriorOp, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtSistContabOp, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCondicionCp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNombreComCp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTipoCp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInscripcionCp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEstadoCp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDireccionCp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSistEmisionCp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActExteriorCp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSistContabCp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEmiElectCp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPLECp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTipoPersonaCp, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnRazonSocialCp, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(txtRucInput, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarRuc, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLiampiarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRucCp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtRucOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRazonSocialCp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRazonSocialOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtTipoPersonaOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnTipoPersonaCp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtCondicionOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnCondicionCp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNombreComOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNombreComCp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTipoOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTipoCp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(txtInscripcionOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnInscripcionCp, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txtEstadoOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnEstadoCp, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtDireccionOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnDireccionCp, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(txtSistEmisionOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSistEmisionCp, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(txtActExteriorOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnActExteriorCp, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(txtSistContabOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSistContabCp, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtEmiElectOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEmiElectCp, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(txtPLEOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnPLECp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(50, 50, 50))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblLoadingAnimation))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(lblLoadingText)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
    * Java procesa todos los eventos de ratón y teclado en un hilo aparte conocido como hilo de despacho de eventos (EDT).
    * El problema de este mecanismo es que si ante un evento de ratón o teclado realizamos una tarea que tarde mucho tiempo, 
    * durante todo ese tiempo, el EDT está haciendo nuestra tarea y, por tanto, no está repintando las ventanas ni atendiendo a otros eventos de teclado o ratón. 
    * El resultado es que mientras realizamos esa tarea, nuestra ventana no responde a eventos de teclado o ratón y no se repinta si pasamos otra ventana por encima. 
    * Este efecto dura hasta que terminemos de realizar nuestra tarea.
    * ----------
    * Método que crea un worker para ejecutar el proceso de búsqueda en segundo plano.
    * La finalidad es evitar el "freeze" al momento de dar click al botón buscar.
    */
    private void createWorker(){
        buscarRucWorker = new SwingWorker<Void, Integer>() {          
            /*
             * Ejecuta el Event Dispatch Thread (EDT)
             * El proceso de búsqueda se ejecuta en segundo plano, en un hilo independiente
             */            
            @Override
            protected Void doInBackground() throws Exception {
                //limpia el formulario
                resetFormulario();
                //desactiva botón de búsqueda
                btnBuscarRuc.setEnabled(false);
                //desactiva el input del RUC
                txtRucInput.setEnabled(false);
                //desactiva el botón de limpieza
                btnLiampiarTodo.setEnabled(false);
                
                //Si el ruc empieza con 20, aplicará la clase SunatJuridica
                if (txtRucInput.getText().startsWith("20")){
                    //Instanciamos con la clase SunatJuridica
                    oSuJuridica = new SunatJuridica(txtRucInput.getText());

                    //Verifica que la respuesta de la API sea "true"
                    if ("true".equals(oSuJuridica.parse().get(0).get(0).get("successResult"))){              
                        //seteamos las variables con la información obtenida de la clase
                        String apRuc = oSuJuridica.parse().get(0).get(0).get("ruc");
                        String apRazonSocial = oSuJuridica.parse().get(0).get(0).get("razonSocial");
                        String apTipoDePersona = oSuJuridica.parse().get(0).get(0).get("tipoDePersona");
                        String apCondicion = oSuJuridica.parse().get(0).get(0).get("condicion");
                        String apNombreComercial = oSuJuridica.parse().get(0).get(0).get("nombreComercial");
                        String apTipo = oSuJuridica.parse().get(0).get(0).get("tipo");
                        String apInscripcion = oSuJuridica.parse().get(0).get(0).get("inscripcion");
                        String apEstado = oSuJuridica.parse().get(0).get(0).get("estado");
                        String apDireccion = oSuJuridica.parse().get(0).get(0).get("direccion");
                        String apSistemEmision = oSuJuridica.parse().get(0).get(0).get("sistemaEmision");
                        String apActividadExterior = oSuJuridica.parse().get(0).get(0).get("actividadExterior");
                        String apSistemaContabilidad = oSuJuridica.parse().get(0).get(0).get("sistemaContabilidad");
                        String apEmisionElectronica = oSuJuridica.parse().get(0).get(0).get("emisionElectronica");
                        String apPLE = oSuJuridica.parse().get(0).get(0).get("ple");

                        procesador(apRuc, txtRucOp, btnRucCp);
                        procesador(apRazonSocial, txtRazonSocialOp, btnRazonSocialCp);
                        procesador(apTipoDePersona, txtTipoPersonaOp, btnTipoPersonaCp);
                        procesador(apCondicion, txtCondicionOp, btnCondicionCp);
                        procesador(apNombreComercial, txtNombreComOp, btnNombreComCp);
                        procesador(apTipo, txtTipoOp, btnTipoCp);
                        procesador(apInscripcion, txtInscripcionOp, btnInscripcionCp);
                        procesador(apEstado, txtEstadoOp, btnEstadoCp);
                        procesador(apDireccion, txtDireccionOp, btnDireccionCp);
                        procesador(apSistemEmision, txtSistEmisionOp, btnSistEmisionCp);
                        procesador(apActividadExterior, txtActExteriorOp, btnActExteriorCp);
                        procesador(apSistemaContabilidad, txtSistContabOp, btnSistContabCp);
                        procesador(apEmisionElectronica, txtEmiElectOp, btnEmiElectCp);
                        procesador(apPLE, txtPLEOp, btnPLECp);
                    } else {
                        String apiSucc = oSuJuridica.parse().get(0).get(0).get("successResult");
                        JOptionPane.showMessageDialog(null, "["+oSuJuridica.parse().get(0).get(0).get("apiMsg")+"]", "API Response: " + apiSucc, JOptionPane.INFORMATION_MESSAGE);
                    }   
                //Caso contrario aplicará la clase "SunatNatural"
                }else {
                    //Instanciamos con la clase SunatNatural
                    oSuNatural = new SunatNatural(txtRucInput.getText());

                    //Verifica que la respuesta de la API sea "true"
                    if ("true".equals(oSuNatural.parse().get(0).get(0).get("successResult"))){               
                        //seteamos las variables con la información obtenida de la clase
                        String apRuc = oSuNatural.parse().get(0).get(0).get("ruc");
                        String apRazonSocial = oSuNatural.parse().get(0).get(0).get("razonSocial");
                        String apTipoDePersona = oSuNatural.parse().get(0).get(0).get("tipoDePersona");
                        String apCondicion = oSuNatural.parse().get(0).get(0).get("condicion");
                        String apNombreComercial = oSuNatural.parse().get(0).get(0).get("nombreComercial");
                        String apTipo = oSuNatural.parse().get(0).get(0).get("tipo");
                        String apInscripcion = oSuNatural.parse().get(0).get(0).get("inscripcion");
                        String apEstado = oSuNatural.parse().get(0).get(0).get("estado");
                        String apDireccion = oSuNatural.parse().get(0).get(0).get("direccion");
                        String apSistemEmision = oSuNatural.parse().get(0).get(0).get("sistemaEmision");
                        String apActividadExterior = oSuNatural.parse().get(0).get(0).get("actividadExterior");
                        String apSistemaContabilidad = oSuNatural.parse().get(0).get(0).get("sistemaContabilidad");
                        String apEmisionElectronica = oSuNatural.parse().get(0).get(0).get("emisionElectronica");

                        procesador(apRuc, txtRucOp, btnRucCp);
                        procesador(apRazonSocial, txtRazonSocialOp, btnRazonSocialCp);
                        procesador(apTipoDePersona, txtTipoPersonaOp, btnTipoPersonaCp);
                        procesador(apCondicion, txtCondicionOp, btnCondicionCp);
                        procesador(apNombreComercial, txtNombreComOp, btnNombreComCp);
                        procesador(apTipo, txtTipoOp, btnTipoCp);
                        procesador(apInscripcion, txtInscripcionOp, btnInscripcionCp);
                        procesador(apEstado, txtEstadoOp, btnEstadoCp);
                        procesador(apDireccion, txtDireccionOp, btnDireccionCp);
                        procesador(apSistemEmision, txtSistEmisionOp, btnSistEmisionCp);
                        procesador(apActividadExterior, txtActExteriorOp, btnActExteriorCp);
                        procesador(apSistemaContabilidad, txtSistContabOp, btnSistContabCp);
                        procesador(apEmisionElectronica, txtEmiElectOp, btnEmiElectCp);
                    } else {
                        String apiSucc = oSuNatural.parse().get(0).get(0).get("successResult");
                        JOptionPane.showMessageDialog(null, "["+oSuNatural.parse().get(0).get(0).get("apiMsg")+"]", "API Response: " + apiSucc, JOptionPane.INFORMATION_MESSAGE);
                    }                
                }
                return null;
            }
         
            /*
             * Ejecuta el Event Dispatch Thread (EDT)
             * Cuando el proceso haya terminado, ocultar el gif
             */
            @Override
            protected void done() {
                //Oculta animación de carga
                lblLoadingAnimation.setVisible(false);
                //Oculta texto de carga
                lblLoadingText.setVisible(false);
                //activa botón de búsqueda
                btnBuscarRuc.setEnabled(true);
                //activa input el input del RUC
                txtRucInput.setEnabled(true);
                //activa el botón de limpieza
                btnLiampiarTodo.setEnabled(true);
                super.done();
            }            
        };
    }
    
    //con este método verificamos que la data obtenida no esté vacía y no empiece con un "-"
    //el método recibe como parámetro un tipo JTextField y un JButton
    private void procesador(String strGetDato, JTextField oFieldText, JButton oButton){
            if (!strGetDato.isEmpty() && !strGetDato.startsWith("-")){
                oFieldText.setText(strGetDato);
                oButton.setEnabled(true);
            }  
    }  
    
    //Sobreescribe el método "actionPerformed"
    //Tanto JTextField como JButton, fueron diseñados para usar un "ActionListener"
    Action buscarRucAction = new AbstractAction()
    {
        @Override
        public void actionPerformed(ActionEvent e)
        {
            //Creo el worker
            createWorker();
            //Muestra animación de carga
            lblLoadingAnimation.setVisible(true);     
            //Muestro el texto de carga
            lblLoadingText.setVisible(true);
            //Ejecuta el worker
            buscarRucWorker.execute();
        }
    };    
    
    //Sobreescribe el método "actionPerformed"
    //Verifica el origen de quien lo está invocando
    //Dependiendo del botón que lo invoca, copia al clipboard el texto del JTextField correspondiente
    Action copyToClipboard = new AbstractAction()
    {
        @Override
        public void actionPerformed(ActionEvent e)
        {
            if(e.getSource() == btnRucCp){
                getCopyToClipboard(txtRucOp);
            } else if (e.getSource() == btnRazonSocialCp){
                getCopyToClipboard(txtRazonSocialOp);
            } else if (e.getSource() == btnTipoPersonaCp){
                getCopyToClipboard(txtTipoPersonaOp);
            } else if (e.getSource() == btnCondicionCp){
                getCopyToClipboard(txtCondicionOp);
            } else if (e.getSource() == btnNombreComCp){
                getCopyToClipboard(txtNombreComOp);
            } else if (e.getSource() == btnTipoCp){
                getCopyToClipboard(txtTipoOp);
            } else if (e.getSource() == btnInscripcionCp){
                getCopyToClipboard(txtInscripcionOp);
            } else if (e.getSource() == btnEstadoCp){
                getCopyToClipboard(txtEstadoOp);
            } else if (e.getSource() == btnDireccionCp){
                getCopyToClipboard(txtDireccionOp);
            } else if (e.getSource() == btnSistEmisionCp){
                getCopyToClipboard(txtSistEmisionOp);
            } else if (e.getSource() == btnActExteriorCp){
                getCopyToClipboard(txtActExteriorOp);
            } else if (e.getSource() == btnSistContabCp){
                getCopyToClipboard(txtSistContabOp);
            } else if (e.getSource() == btnEmiElectCp){
                getCopyToClipboard(txtEmiElectOp);
            } else if (e.getSource() == btnPLECp){
                getCopyToClipboard(txtPLEOp);
            }
        }
    };  
    
    //Método que recibe como parámetro un JTextField y copia su contenido al Clipboard
    private void getCopyToClipboard(JTextField oFieldText){
        String contenido = oFieldText.getText();
        StringSelection seContenido = new StringSelection(contenido);
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clipboard.setContents(seContenido, null);
    }
    
    //Activa el botón de buscar cuando haya texto en el input
    private void txtRucInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRucInputKeyTyped
        if (txtRucInput.getText().isEmpty()){
            btnBuscarRuc.setEnabled(false);
        } else {
            btnBuscarRuc.setEnabled(true);
        }     
    }//GEN-LAST:event_txtRucInputKeyTyped

    //Detecta si se ha introducido letras o espacios en blanco en el campo de búsqueda
    private void txtRucInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRucInputKeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c) || c == ' '){
            txtRucInput.setEditable(false);
            JOptionPane.showMessageDialog(null, "Este campo solo admite números enteros.", "Información: " + "Texto Inválido", JOptionPane.INFORMATION_MESSAGE);
        } else {
            txtRucInput.setEditable(true);
        }
    }//GEN-LAST:event_txtRucInputKeyPressed

    //Limpia todo el formulario
    private void btnLiampiarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLiampiarTodoActionPerformed
        //Limpiamos formulario
        resetFormulario();
    }//GEN-LAST:event_btnLiampiarTodoActionPerformed

    //Método para limpiar y restablecer todos los campos del formulario
    private void resetFormulario(){
        //reset Cajas de texto
        txtRucOp.setText("-");
        txtRazonSocialOp.setText("-");
        txtTipoPersonaOp.setText("-");
        txtCondicionOp.setText("-");
        txtNombreComOp.setText("-");
        txtTipoOp.setText("-");
        txtInscripcionOp.setText("-");
        txtEstadoOp.setText("-");
        txtDireccionOp.setText("-");
        txtSistEmisionOp.setText("-");
        txtActExteriorOp.setText("-");
        txtSistContabOp.setText("-");
        txtEmiElectOp.setText("-");
        txtPLEOp.setText("-");
        
        //reset Botones de copiar
        btnRucCp.setEnabled(false);
        btnRazonSocialCp.setEnabled(false);
        btnTipoPersonaCp.setEnabled(false);
        btnCondicionCp.setEnabled(false);
        btnNombreComCp.setEnabled(false);
        btnTipoCp.setEnabled(false);
        btnInscripcionCp.setEnabled(false);
        btnEstadoCp.setEnabled(false);
        btnDireccionCp.setEnabled(false);
        btnSistEmisionCp.setEnabled(false);
        btnActExteriorCp.setEnabled(false);
        btnSistContabCp.setEnabled(false);
        btnEmiElectCp.setEnabled(false);
        btnPLECp.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActExteriorCp;
    private javax.swing.JButton btnBuscarRuc;
    private javax.swing.JButton btnCondicionCp;
    private javax.swing.JButton btnDireccionCp;
    private javax.swing.JButton btnEmiElectCp;
    private javax.swing.JButton btnEstadoCp;
    private javax.swing.JButton btnInscripcionCp;
    private javax.swing.JButton btnLiampiarTodo;
    private javax.swing.JButton btnNombreComCp;
    private javax.swing.JButton btnPLECp;
    private javax.swing.JButton btnRazonSocialCp;
    private javax.swing.JButton btnRucCp;
    private javax.swing.JButton btnSistContabCp;
    private javax.swing.JButton btnSistEmisionCp;
    private javax.swing.JButton btnTipoCp;
    private javax.swing.JButton btnTipoPersonaCp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLoadingAnimation;
    private javax.swing.JLabel lblLoadingText;
    private javax.swing.JTextField txtActExteriorOp;
    private javax.swing.JTextField txtCondicionOp;
    private javax.swing.JTextField txtDireccionOp;
    private javax.swing.JTextField txtEmiElectOp;
    private javax.swing.JTextField txtEstadoOp;
    private javax.swing.JTextField txtInscripcionOp;
    private javax.swing.JTextField txtNombreComOp;
    private javax.swing.JTextField txtPLEOp;
    private javax.swing.JTextField txtRazonSocialOp;
    private javax.swing.JTextField txtRucInput;
    private javax.swing.JTextField txtRucOp;
    private javax.swing.JTextField txtSistContabOp;
    private javax.swing.JTextField txtSistEmisionOp;
    private javax.swing.JTextField txtTipoOp;
    private javax.swing.JTextField txtTipoPersonaOp;
    // End of variables declaration//GEN-END:variables
}
